package deluxe;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

// $FF: synthetic class
public class AttackUI extends JFrame {
   public JButton btnFriendStop;
   public static final long serialVersionUID = 1L;
   public static boolean friendSpam = false;
   public JButton btnStartServerSpam;
   public static SpamUtils su = new N();
   public JButton btnFriendStart;
   public JPanel contentPane;
   public static boolean serverSpam = false;
   public JButton btnStopServerSpam;

   public AttackUI() {
      this.setTitle("New attack");
      this.setDefaultCloseOperation(1);
      this.setBounds(100, 100, 437, 365);
      Dimension var1 = Toolkit.getDefaultToolkit().getScreenSize();
      this.setLocation(var1.width / 2 - this.getSize().width / 2, var1.height / 2 - this.getSize().height / 2);
      this.setResizable(false);
      this.contentPane = new JPanel();
      this.contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
      this.setContentPane(this.contentPane);
      this.contentPane.setLayout((LayoutManager)null);
      JTabbedPane var2 = new JTabbedPane(1);
      var2.setBounds(0, 0, 434, 336);
      this.contentPane.add(var2);
      JPanel var3 = new JPanel();
      var2.addTab("Join", new ImageIcon(this.getClass().getResource("/ui/notchecked.png")), var3, (String)null);
      var3.setLayout((LayoutManager)null);
      JLabel var4 = new JLabel("Invite link (https://discord.gg/...) OR invite code");
      var4.setBounds(71, 97, 291, 14);
      var3.add(var4);
      JTextField var5 = new JTextField();
      var5.setBounds(70, 112, 292, 33);
      var3.add(var5);
      var5.setColumns(10);
      JButton var6 = new JButton("Join");
      var6.addActionListener(new AY(this, var5));
      var6.setBackground(Color.DARK_GRAY);
      var6.setBounds(70, 156, 292, 33);
      var3.add(var6);
      JPanel var7 = new JPanel();
      var2.addTab("Leave", new ImageIcon(this.getClass().getResource("/ui/notchecked.png")), var7, (String)null);
      var7.setLayout((LayoutManager)null);
      JLabel var8 = new JLabel("Server id (Guild id)");
      var8.setBounds(70, 93, 291, 14);
      var7.add(var8);
      JTextField var9 = new JTextField();
      var9.setColumns(10);
      var9.setBounds(69, 108, 292, 33);
      var7.add(var9);
      JButton var10 = new JButton("Leave");
      var10.addActionListener(new L(this, var9));
      var10.setBackground(Color.DARK_GRAY);
      var10.setBounds(69, 152, 292, 33);
      var7.add(var10);
      JPanel var11 = new JPanel();
      var2.addTab("Server spam", new ImageIcon(this.getClass().getResource("/ui/notchecked.png")), var11, (String)null);
      var11.setLayout((LayoutManager)null);
      JLabel var12 = new JLabel("Channel id");
      var12.setBounds(36, 11, 291, 14);
      var11.add(var12);
      JTextField var13 = new JTextField();
      var13.setColumns(10);
      var13.setBounds(36, 26, 360, 27);
      var11.add(var13);
      JTextArea var14 = new JTextArea();
      JScrollPane var15 = new JScrollPane(var14, 22, 30);
      var15.setBounds(36, 64, 360, 112);
      var11.add(var15);
      JLabel var16 = new JLabel("Delay: 2100 ms");
      var16.setBounds(180, 182, 100, 14);
      var11.add(var16);
      JSlider var17 = new JSlider();
      var17.addChangeListener(new AP(this, var16, var17));
      var17.setMaximum(5000);
      var17.setMinimum(2100);
      var17.setBounds(30, 196, 371, 26);
      var11.add(var17);
      JLabel var18 = new JLabel("Fastest");
      var18.setBounds(36, 222, 46, 14);
      var11.add(var18);
      JLabel var19 = new JLabel("Slowest");
      var19.setBounds(361, 222, 46, 14);
      var11.add(var19);
      JCheckBox var20 = new JCheckBox("TTS (Text to Speech)");
      var20.setBounds(147, 232, 189, 23);
      var11.add(var20);
      this.btnStartServerSpam = new JButton("Start");
      this.btnStartServerSpam.addActionListener(new I(this, var13, var14, var20, var17));
      this.btnStartServerSpam.setBackground(Color.GREEN);
      this.btnStartServerSpam.setBounds(223, 262, 173, 33);
      var11.add(this.btnStartServerSpam);
      this.btnStopServerSpam = new JButton("Stop");
      this.btnStopServerSpam.addActionListener(new Q(this));
      this.btnStopServerSpam.setEnabled(false);
      this.btnStopServerSpam.setBackground(Color.RED);
      this.btnStopServerSpam.setBounds(36, 262, 173, 33);
      var11.add(this.btnStopServerSpam);
      JPanel var21 = new JPanel();
      var2.addTab("Friend request spam", new ImageIcon(this.getClass().getResource("/ui/notchecked.png")), var21, (String)null);
      var21.setLayout((LayoutManager)null);
      JLabel var22 = new JLabel("User id");
      var22.setBounds(63, 94, 291, 14);
      var21.add(var22);
      JTextField var23 = new JTextField();
      var23.setColumns(10);
      var23.setBounds(62, 109, 292, 33);
      var21.add(var23);
      this.btnFriendStop = new JButton("Stop");
      this.btnFriendStop.addActionListener(new T(this));
      this.btnFriendStop.setEnabled(false);
      this.btnFriendStop.setBackground(Color.RED);
      this.btnFriendStop.setBounds(63, 153, 134, 33);
      var21.add(this.btnFriendStop);
      this.btnFriendStart = new JButton("Start");
      this.btnFriendStart.addActionListener(new U(this, var23));
      this.btnFriendStart.setBackground(Color.GREEN);
      this.btnFriendStart.setBounds(220, 153, 134, 33);
      var21.add(this.btnFriendStart);
   }
}
